apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gt6cm8s0a-nodejs
  janus-idp.io/tekton: gt6cm8s0a-nodejs
  backstage.io/kubernetes-id: gt6cm8s0a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gt6cm8s0a-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
